### ISSUE TITLE
# Error Adding Data to Seurat Object 

### ISSUE THREAD

**Issue by Saindhabi17** [Saindhabi17/SCRNA_repo#3]
How to get the indexing information after adding two objects?

**Comment by hamidghaedi** [comment]
Not sure if I got what you mean by indexing... could you please provide the code that you have tried to do the task and the error(if any), so I can help. If you are inquiring about any previous Issues that I closed, feel free to reopen that and add your relevant question/issue there.

P.S let's save this space (Issue @ GitHub repo) for code review and related troubleshooting.

**Comment by Saindhabi17** [comment]
Yes, I think there can be some issue with the code using for adding the data frame. As before adding the data, seurat_integrated file contained the indexing info.

I am posting the code once again.
```R
tmp_df<- seurat_integrated@meta.data
merged_df <- merge(tmp_df, sampleData, 
                   by.x = "orig.ident", 
                   by.y = "sample_id", 
                   all.x = TRUE)
seurat_integrated@meta.data<-merged_df

saveRDS(seurat_integrated, "seurat_integrated.RDS")
```
I am not sure whether there is any issue or not. Do I need to do any further steps after that? 

P.s.: Is'nt his space is autosaved? As I am not finding something to save here.

**Comment by hamidghaedi** [comment]
Can you specify what indexes are gone after running the above command?

**Comment by Saindhabi17** [comment]
Before adding the sample data with seurat_integrated, there was a column before ```orig.ident ```
It contained information like ```SRR12603780_AAACCTGAGGACTGGT-1```

After joining, it is missing. Instead, there is simple indexing now, like 1,2...

**Comment by hamidghaedi** [comment]
I see, you need to re-assign rownames to the metadata, something like the following should work:

`rownames(seurat_obj@meta.data) <- seurat_obj@meta.data$cells`

**Comment by Saindhabi17** [comment]
Yes it is working. I am closing this issue.
